<?php

/** @var \Joomla\Registry\Registry $params */
/** @var \stdClass $module */
\defined('_JEXEC') or die;

echo $params->get('title');

?>
-----
<?php

/** @var \Joomla\CMS\Application\CMSApplicationInterface $app */
/** @var \Joomla\Input\Input $input */
/** @var string $template */
/** @var \stdClass[] $items */
/** @var \Joomla\Registry\Registry $params */
/** @var \stdClass $module */
\defined('_JEXEC') or die;

echo $params->get('title');

?>
