<?php

/**
 * @package     Acme.Site
 * @subpackage  mod_foo
 *
 * @copyright   (C) 2026 Acme, Inc.
 * @license     GNU General Public License version 2 or later
 */

\defined('_JEXEC') or die;

echo $params->get('title');

?>
-----
<?php

/**
 * @package     Acme.Site
 * @subpackage  mod_foo
 *
 * @copyright   (C) 2026 Acme, Inc.
 * @license     GNU General Public License version 2 or later
 */
/** @var \stdClass $module */
/** @var \Joomla\CMS\Application\CMSApplicationInterface $app */
/** @var \Joomla\Input\Input $input */
/** @var \Joomla\Registry\Registry $params */
/** @var string $template */
/** @var \stdClass[] $items */
\defined('_JEXEC') or die;

echo $params->get('title');

?>
