<?php

/**
 * @package     Joomla.Rector
 * @subpackage  Joomla6
 *
 * @copyright   (C) 2026 Open Source Matters, Inc. <https://www.joomla.org>
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

declare(strict_types=1);

namespace Joomla\Rector\Joomla6\Event;

use PHPStan\Reflection\ReflectionProvider;

/**
 * Shared knowledge about the Joomla event classes, used by every plugin event rule.
 *
 * Holds two generated maps:
 *
 *   - DEFAULT_EVENT_ARGUMENT_MAP — per event class the positional argument order, the
 *     argument name => getter mapping, and whether the event carries the addResult() API.
 *   - DEFAULT_EVENT_NAME_MAP — event name => concrete event class.
 *
 * Both are generated from the Joomla core source by tools/generate-event-argument-map.php.
 * The getter name cannot be derived from the argument name — ContentPrepareEvent stores its
 * argument as `subject` but exposes it as getItem() — which is why the map is read out of the
 * getter bodies rather than guessed, and why reflection alone cannot replace it.
 *
 * This class holds no per-rule state: the merged map is owned by each rule, so two rules
 * configured differently cannot interfere with each other.
 *
 * @since  1.0.0
 */
final class JoomlaEventMap
{
    /**
     * Event classes that are too generic to determine a concrete argument list from.
     */
    public const GENERIC_EVENT_CLASSES = [
        'Joomla\\Event\\Event',
        'Joomla\\Event\\EventInterface',
        'Joomla\\Event\\AbstractEvent',
        'Joomla\\Event\\EventImmutable',
        'Joomla\\CMS\\Event\\AbstractEvent',
        'Joomla\\CMS\\Event\\AbstractImmutableEvent',
        'Joomla\\CMS\\Event\\GenericEvent',
    ];

    // <generated:ARGUMENT_MAP>
    /**
     * Argument map for the Joomla core events.
     *
     * `order` is the positional argument order taken from $legacyArgumentsOrder, `getters`
     * maps an argument name onto its getter, and `resultAware` says whether the event
     * carries the addResult() API of ResultAwareInterface.
     *
     * Generated by tools/generate-event-argument-map.php from Joomla 6.1.1.
     * Do not edit by hand — re-run the generator instead.
     *
     * @var array<class-string, array{order: string[], getters: array<string, string>, resultAware: bool}>
     */
    public const DEFAULT_EVENT_ARGUMENT_MAP = [
        'Joomla\\CMS\\Event\\AfterExtensionBootEvent' => [
            'order'       => [],
            'getters'     => ['type' => 'getExtensionType', 'extensionName' => 'getExtensionName', 'container' => 'getContainer'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Application\\AfterApiRouteEvent' => [
            'order'       => [],
            'getters'     => ['subject' => 'getApplication'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Application\\AfterCompressEvent' => [
            'order'       => [],
            'getters'     => ['subject' => 'getApplication'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Application\\AfterDispatchEvent' => [
            'order'       => [],
            'getters'     => ['subject' => 'getApplication'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Application\\AfterExecuteEvent' => [
            'order'       => [],
            'getters'     => ['subject' => 'getApplication'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Application\\AfterInitialiseDocumentEvent' => [
            'order'       => [],
            'getters'     => ['subject' => 'getApplication', 'document' => 'getDocument'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Application\\AfterInitialiseEvent' => [
            'order'       => [],
            'getters'     => ['subject' => 'getApplication'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Application\\AfterRenderEvent' => [
            'order'       => [],
            'getters'     => ['subject' => 'getApplication'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Application\\AfterRespondEvent' => [
            'order'       => [],
            'getters'     => ['subject' => 'getApplication'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Application\\AfterRouteEvent' => [
            'order'       => [],
            'getters'     => ['subject' => 'getApplication'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Application\\AfterSaveConfigurationEvent' => [
            'order'       => [],
            'getters'     => ['subject' => 'getConfiguration'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Application\\ApplicationConfigurationEvent' => [
            'order'       => [],
            'getters'     => ['subject' => 'getConfiguration'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Application\\ApplicationDocumentEvent' => [
            'order'       => [],
            'getters'     => ['subject' => 'getApplication', 'document' => 'getDocument'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Application\\ApplicationEvent' => [
            'order'       => [],
            'getters'     => ['subject' => 'getApplication'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Application\\BeforeApiRouteEvent' => [
            'order'       => [],
            'getters'     => ['subject' => 'getApplication', 'router' => 'getRouter'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Application\\BeforeCompileHeadEvent' => [
            'order'       => [],
            'getters'     => ['subject' => 'getApplication', 'document' => 'getDocument'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Application\\BeforeExecuteEvent' => [
            'order'       => [],
            'getters'     => ['subject' => 'getApplication', 'container' => 'getContainer'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Application\\BeforeRenderEvent' => [
            'order'       => [],
            'getters'     => ['subject' => 'getApplication'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Application\\BeforeRespondEvent' => [
            'order'       => [],
            'getters'     => ['subject' => 'getApplication'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Application\\BeforeSaveConfigurationEvent' => [
            'order'       => [],
            'getters'     => ['subject' => 'getConfiguration'],
            'resultAware' => true,
        ],
        'Joomla\\CMS\\Event\\Application\\DaemonForkEvent' => [
            'order'       => [],
            'getters'     => ['subject' => 'getApplication'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Application\\DaemonReceiveSignalEvent' => [
            'order'       => [],
            'getters'     => ['subject' => 'getApplication', 'signal' => 'getSignal'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\BeforeExtensionBootEvent' => [
            'order'       => [],
            'getters'     => ['type' => 'getExtensionType', 'extensionName' => 'getExtensionName', 'container' => 'getContainer'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Cache\\AfterPurgeEvent' => [
            'order'       => ['subject'],
            'getters'     => ['subject' => 'getGroup'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Captcha\\CaptchaSetupEvent' => [
            'order'       => [],
            'getters'     => ['subject' => 'getCaptchaRegistry'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Checkin\\AfterCheckinEvent' => [
            'order'       => ['subject'],
            'getters'     => ['subject' => 'getTableName'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Contact\\SubmitContactEvent' => [
            'order'       => ['subject', 'data'],
            'getters'     => ['subject' => 'getContact', 'data' => 'getData'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Contact\\ValidateContactEvent' => [
            'order'       => ['subject', 'data'],
            'getters'     => ['subject' => 'getContact', 'data' => 'getData'],
            'resultAware' => true,
        ],
        'Joomla\\CMS\\Event\\Content\\AfterDisplayEvent' => [
            'order'       => ['context', 'subject', 'params', 'page'],
            'getters'     => ['context' => 'getContext', 'subject' => 'getItem', 'params' => 'getParams', 'page' => 'getPage'],
            'resultAware' => true,
        ],
        'Joomla\\CMS\\Event\\Content\\AfterTitleEvent' => [
            'order'       => ['context', 'subject', 'params', 'page'],
            'getters'     => ['context' => 'getContext', 'subject' => 'getItem', 'params' => 'getParams', 'page' => 'getPage'],
            'resultAware' => true,
        ],
        'Joomla\\CMS\\Event\\Content\\BeforeDisplayEvent' => [
            'order'       => ['context', 'subject', 'params', 'page'],
            'getters'     => ['context' => 'getContext', 'subject' => 'getItem', 'params' => 'getParams', 'page' => 'getPage'],
            'resultAware' => true,
        ],
        'Joomla\\CMS\\Event\\Content\\ContentEvent' => [
            'order'       => [],
            'getters'     => ['context' => 'getContext'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Content\\ContentPrepareEvent' => [
            'order'       => ['context', 'subject', 'params', 'page'],
            'getters'     => ['context' => 'getContext', 'subject' => 'getItem', 'params' => 'getParams', 'page' => 'getPage'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\CustomFields\\AbstractPrepareFieldEvent' => [
            'order'       => ['context', 'item', 'subject'],
            'getters'     => ['subject' => 'getField', 'context' => 'getContext', 'item' => 'getItem'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\CustomFields\\AfterPrepareFieldEvent' => [
            'order'       => ['context', 'item', 'subject', 'value'],
            'getters'     => ['subject' => 'getField', 'context' => 'getContext', 'item' => 'getItem', 'value' => 'getValue'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\CustomFields\\BeforePrepareFieldEvent' => [
            'order'       => ['context', 'item', 'subject'],
            'getters'     => ['subject' => 'getField', 'context' => 'getContext', 'item' => 'getItem'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\CustomFields\\PrepareDomEvent' => [
            'order'       => ['subject', 'fieldset', 'form'],
            'getters'     => ['subject' => 'getField', 'fieldset' => 'getFieldset', 'form' => 'getForm'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\CustomFields\\PrepareFieldEvent' => [
            'order'       => ['context', 'item', 'subject'],
            'getters'     => ['subject' => 'getField', 'context' => 'getContext', 'item' => 'getItem'],
            'resultAware' => true,
        ],
        'Joomla\\CMS\\Event\\Editor\\EditorButtonsSetupEvent' => [
            'order'       => [],
            'getters'     => ['subject' => 'getButtonsRegistry', 'editorType' => 'getEditorType', 'disabledButtons' => 'getDisabledButtons', 'editorId' => 'getEditorId', 'asset' => 'getAsset', 'author' => 'getAuthor'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Editor\\EditorSetupEvent' => [
            'order'       => [],
            'getters'     => ['subject' => 'getEditorsRegistry'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\ErrorEvent' => [
            'order'       => [],
            'getters'     => ['application' => 'getApplication', 'subject' => 'getError'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Extension\\AfterInstallEvent' => [
            'order'       => ['installer', 'eid'],
            'getters'     => ['installer' => 'getInstaller', 'eid' => 'getEid'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Extension\\AfterJoomlaUpdateEvent' => [
            'order'       => ['oldVersion'],
            'getters'     => ['oldVersion' => 'getOldVersion'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Extension\\AfterUninstallEvent' => [
            'order'       => ['installer', 'eid', 'removed'],
            'getters'     => ['installer' => 'getInstaller', 'eid' => 'getEid', 'removed' => 'getRemoved'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Extension\\AfterUpdateEvent' => [
            'order'       => ['installer', 'eid'],
            'getters'     => ['installer' => 'getInstaller', 'eid' => 'getEid'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Extension\\BeforeInstallEvent' => [
            'order'       => ['method', 'type', 'manifest', 'extension'],
            'getters'     => ['method' => 'getMethod', 'type' => 'getType', 'manifest' => 'getManifest', 'extension' => 'getExtension'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Extension\\BeforeUninstallEvent' => [
            'order'       => ['eid'],
            'getters'     => ['eid' => 'getEid'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Extension\\BeforeUpdateEvent' => [
            'order'       => ['type', 'manifest'],
            'getters'     => ['type' => 'getType', 'manifest' => 'getManifest'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Finder\\AfterChangeStateEvent' => [
            'order'       => ['context', 'subject', 'value'],
            'getters'     => ['context' => 'getContext', 'subject' => 'getPks', 'value' => 'getValue'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Finder\\AfterDeleteEvent' => [
            'order'       => ['context', 'subject'],
            'getters'     => ['context' => 'getContext', 'subject' => 'getItem'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Finder\\AfterSaveEvent' => [
            'order'       => ['context', 'subject', 'isNew'],
            'getters'     => ['context' => 'getContext', 'subject' => 'getItem', 'isNew' => 'getIsNew', 'data' => 'getData'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Finder\\BeforeSaveEvent' => [
            'order'       => ['context', 'subject', 'isNew'],
            'getters'     => ['context' => 'getContext', 'subject' => 'getItem', 'isNew' => 'getIsNew', 'data' => 'getData'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Finder\\PrepareContentEvent' => [
            'order'       => ['subject'],
            'getters'     => ['subject' => 'getItem'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Finder\\ResultEvent' => [
            'order'       => ['subject', 'query'],
            'getters'     => ['subject' => 'getItem', 'query' => 'getQuery'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Installer\\AfterInstallerEvent' => [
            'order'       => ['subject', 'package', 'installer', 'installerResult', 'message'],
            'getters'     => ['subject' => 'getModel', 'package' => 'getPackage', 'installer' => 'getInstaller', 'installerResult' => 'getInstallerResult', 'message' => 'getMessage'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Installer\\BeforeInstallationEvent' => [
            'order'       => ['subject', 'package'],
            'getters'     => ['subject' => 'getModel', 'package' => 'getPackage'],
            'resultAware' => true,
        ],
        'Joomla\\CMS\\Event\\Installer\\BeforeInstallerEvent' => [
            'order'       => ['subject', 'package'],
            'getters'     => ['subject' => 'getModel', 'package' => 'getPackage'],
            'resultAware' => true,
        ],
        'Joomla\\CMS\\Event\\Installer\\BeforePackageDownloadEvent' => [
            'order'       => ['url', 'headers'],
            'getters'     => ['url' => 'getUrl', 'headers' => 'getHeaders'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Installer\\BeforeUpdateSiteDownloadEvent' => [
            'order'       => ['url', 'headers'],
            'getters'     => ['url' => 'getUrl', 'headers' => 'getHeaders'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Installer\\InstallerEvent' => [
            'order'       => ['subject', 'package'],
            'getters'     => ['subject' => 'getModel', 'package' => 'getPackage'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Mail\\BeforeRenderingMailTemplateEvent' => [
            'order'       => ['templateId', 'subject'],
            'getters'     => ['subject' => 'getTemplate', 'templateId' => 'getTemplateId'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Mail\\MailTemplateEvent' => [
            'order'       => [],
            'getters'     => ['subject' => 'getTemplate', 'templateId' => 'getTemplateId'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Menu\\AfterGetMenuTypeOptionsEvent' => [
            'order'       => ['items', 'subject'],
            'getters'     => ['subject' => 'getModel', 'items' => 'getItems'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Menu\\BeforeRenderMenuItemsViewEvent' => [
            'order'       => ['subject'],
            'getters'     => ['subject' => 'getView'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Menu\\PreprocessMenuItemsEvent' => [
            'order'       => ['context', 'subject', 'params', 'enabled'],
            'getters'     => ['context' => 'getContext', 'subject' => 'getItems', 'params' => 'getParams', 'enabled' => 'getEnabled'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Model\\AfterCategoryChangeStateEvent' => [
            'order'       => ['context', 'subject', 'value'],
            'getters'     => ['context' => 'getContext', 'subject' => 'getPks', 'value' => 'getValue'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Model\\AfterChangeStateEvent' => [
            'order'       => ['context', 'subject', 'value'],
            'getters'     => ['context' => 'getContext', 'subject' => 'getPks', 'value' => 'getValue'],
            'resultAware' => true,
        ],
        'Joomla\\CMS\\Event\\Model\\AfterCleanCacheEvent' => [
            'order'       => ['defaultgroup', 'cachebase', 'result'],
            'getters'     => ['defaultgroup' => 'getDefaultGroup', 'cachebase' => 'getCacheBase'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Model\\AfterDeleteEvent' => [
            'order'       => ['context', 'subject'],
            'getters'     => ['context' => 'getContext', 'subject' => 'getItem'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Model\\AfterSaveEvent' => [
            'order'       => ['context', 'subject', 'isNew', 'data'],
            'getters'     => ['context' => 'getContext', 'subject' => 'getItem', 'isNew' => 'getIsNew', 'data' => 'getData'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Model\\BeforeChangeStateEvent' => [
            'order'       => ['context', 'subject', 'value'],
            'getters'     => ['context' => 'getContext', 'subject' => 'getPks', 'value' => 'getValue'],
            'resultAware' => true,
        ],
        'Joomla\\CMS\\Event\\Model\\BeforeDeleteEvent' => [
            'order'       => ['context', 'subject'],
            'getters'     => ['context' => 'getContext', 'subject' => 'getItem'],
            'resultAware' => true,
        ],
        'Joomla\\CMS\\Event\\Model\\BeforeSaveEvent' => [
            'order'       => ['context', 'subject', 'isNew', 'data'],
            'getters'     => ['context' => 'getContext', 'subject' => 'getItem', 'isNew' => 'getIsNew', 'data' => 'getData'],
            'resultAware' => true,
        ],
        'Joomla\\CMS\\Event\\Model\\BeforeValidateDataEvent' => [
            'order'       => ['subject', 'data'],
            'getters'     => ['context' => 'getContext', 'subject' => 'getForm', 'data' => 'getData'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Model\\ChangeStateEvent' => [
            'order'       => ['context', 'subject', 'value'],
            'getters'     => ['context' => 'getContext', 'subject' => 'getPks', 'value' => 'getValue'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Model\\DeleteEvent' => [
            'order'       => ['context', 'subject'],
            'getters'     => ['context' => 'getContext', 'subject' => 'getItem'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Model\\FormEvent' => [
            'order'       => ['subject', 'data'],
            'getters'     => ['context' => 'getContext', 'subject' => 'getForm', 'data' => 'getData'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Model\\ModelEvent' => [
            'order'       => [],
            'getters'     => ['context' => 'getContext'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Model\\NormaliseRequestDataEvent' => [
            'order'       => ['context', 'data', 'subject'],
            'getters'     => ['context' => 'getContext', 'subject' => 'getForm', 'data' => 'getData'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Model\\PrepareDataEvent' => [
            'order'       => ['context', 'data'],
            'getters'     => ['context' => 'getContext', 'data' => 'getData'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Model\\PrepareFormEvent' => [
            'order'       => ['subject', 'data'],
            'getters'     => ['context' => 'getContext', 'subject' => 'getForm', 'data' => 'getData'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Model\\SaveEvent' => [
            'order'       => ['context', 'subject', 'isNew', 'data'],
            'getters'     => ['context' => 'getContext', 'subject' => 'getItem', 'isNew' => 'getIsNew', 'data' => 'getData'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Module\\AfterCleanModuleListEvent' => [
            'order'       => ['modules'],
            'getters'     => ['modules' => 'getModules'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Module\\AfterModuleListEvent' => [
            'order'       => ['modules'],
            'getters'     => ['modules' => 'getModules'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Module\\AfterRenderModuleEvent' => [
            'order'       => ['subject', 'attributes'],
            'getters'     => ['subject' => 'getModule', 'attributes' => 'getAttributes'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Module\\AfterRenderModulesEvent' => [
            'order'       => ['content', 'attributes'],
            'getters'     => ['content' => 'getContent', 'attributes' => 'getAttributes'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Module\\BeforeRenderModuleEvent' => [
            'order'       => ['subject', 'attributes'],
            'getters'     => ['subject' => 'getModule', 'attributes' => 'getAttributes'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Module\\ModuleListEvent' => [
            'order'       => ['modules'],
            'getters'     => ['modules' => 'getModules'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Module\\PrepareModuleListEvent' => [
            'order'       => ['modules'],
            'getters'     => ['modules' => 'getModules'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Module\\RenderModuleEvent' => [
            'order'       => ['subject', 'attributes'],
            'getters'     => ['subject' => 'getModule', 'attributes' => 'getAttributes'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Plugin\\AjaxEvent' => [
            'order'       => [],
            'getters'     => ['subject' => 'getApplication'],
            'resultAware' => true,
        ],
        'Joomla\\CMS\\Event\\Plugin\\System\\Schemaorg\\BeforeCompileHeadEvent' => [
            'order'       => [],
            'getters'     => ['subject' => 'getSchema', 'context' => 'getContext'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Plugin\\System\\Schemaorg\\PrepareDataEvent' => [
            'order'       => [],
            'getters'     => ['subject' => 'getData', 'context' => 'getContext'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Plugin\\System\\Schemaorg\\PrepareFormEvent' => [
            'order'       => [],
            'getters'     => ['subject' => 'getForm'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Plugin\\System\\Schemaorg\\PrepareSaveEvent' => [
            'order'       => [],
            'getters'     => ['subject' => 'getData', 'context' => 'getContext', 'item' => 'getItem', 'isNew' => 'getIsNew', 'schema' => 'getSchema'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Plugin\\System\\Stats\\GetStatsDataEvent' => [
            'order'       => ['context'],
            'getters'     => ['context' => 'getContext'],
            'resultAware' => true,
        ],
        'Joomla\\CMS\\Event\\Privacy\\CanRemoveDataEvent' => [
            'order'       => ['subject', 'user'],
            'getters'     => ['subject' => 'getRequest', 'user' => 'getUser'],
            'resultAware' => true,
        ],
        'Joomla\\CMS\\Event\\Privacy\\CheckPrivacyPolicyPublishedEvent' => [
            'order'       => ['subject'],
            'getters'     => ['subject' => 'getPolicyInfo'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\Privacy\\ExportRequestEvent' => [
            'order'       => ['subject', 'user'],
            'getters'     => ['subject' => 'getRequest', 'user' => 'getUser'],
            'resultAware' => true,
        ],
        'Joomla\\CMS\\Event\\Privacy\\RemoveDataEvent' => [
            'order'       => ['subject', 'user'],
            'getters'     => ['subject' => 'getRequest', 'user' => 'getUser'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\User\\AbstractDeleteEvent' => [
            'order'       => ['subject'],
            'getters'     => ['subject' => 'getUser'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\User\\AbstractLoginEvent' => [
            'order'       => ['subject', 'options'],
            'getters'     => ['subject' => 'getAuthenticationResponse', 'options' => 'getOptions'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\User\\AbstractLogoutEvent' => [
            'order'       => ['subject', 'options'],
            'getters'     => ['subject' => 'getParameters', 'options' => 'getOptions'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\User\\AbstractResetEvent' => [
            'order'       => ['subject'],
            'getters'     => ['subject' => 'getUser'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\User\\AbstractSaveEvent' => [
            'order'       => ['subject', 'isNew'],
            'getters'     => ['subject' => 'getUser', 'isNew' => 'getIsNew'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\User\\AfterDeleteEvent' => [
            'order'       => ['subject', 'deletingResult', 'errorMessage'],
            'getters'     => ['subject' => 'getUser', 'deletingResult' => 'getDeletingResult', 'errorMessage' => 'getErrorMessage'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\User\\AfterLoginEvent' => [
            'order'       => ['options', 'subject'],
            'getters'     => ['subject' => 'getAuthenticationResponse', 'options' => 'getOptions'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\User\\AfterLogoutEvent' => [
            'order'       => ['options', 'subject'],
            'getters'     => ['subject' => 'getParameters', 'options' => 'getOptions'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\User\\AfterRemindEvent' => [
            'order'       => ['subject'],
            'getters'     => ['subject' => 'getUser'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\User\\AfterResetCompleteEvent' => [
            'order'       => ['subject'],
            'getters'     => ['subject' => 'getUser'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\User\\AfterResetRequestEvent' => [
            'order'       => ['subject'],
            'getters'     => ['subject' => 'getUser'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\User\\AfterSaveEvent' => [
            'order'       => ['subject', 'isNew', 'savingResult', 'errorMessage'],
            'getters'     => ['subject' => 'getUser', 'isNew' => 'getIsNew', 'savingResult' => 'getSavingResult', 'errorMessage' => 'getErrorMessage'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\User\\AuthenticationEvent' => [
            'order'       => ['credentials', 'options', 'subject'],
            'getters'     => ['subject' => 'getAuthenticationResponse', 'credentials' => 'getCredentials', 'options' => 'getOptions'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\User\\AuthorisationEvent' => [
            'order'       => ['subject', 'options'],
            'getters'     => ['subject' => 'getAuthenticationResponse', 'options' => 'getOptions'],
            'resultAware' => true,
        ],
        'Joomla\\CMS\\Event\\User\\AuthorisationFailureEvent' => [
            'order'       => ['subject', 'options'],
            'getters'     => ['subject' => 'getAuthenticationResponse', 'options' => 'getOptions'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\User\\BeforeDeleteEvent' => [
            'order'       => ['subject'],
            'getters'     => ['subject' => 'getUser'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\User\\BeforeResetCompleteEvent' => [
            'order'       => ['subject'],
            'getters'     => ['subject' => 'getUser'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\User\\BeforeResetRequestEvent' => [
            'order'       => ['subject'],
            'getters'     => ['subject' => 'getUser'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\User\\BeforeSaveEvent' => [
            'order'       => ['subject', 'isNew', 'data'],
            'getters'     => ['subject' => 'getUser', 'isNew' => 'getIsNew', 'data' => 'getData'],
            'resultAware' => true,
        ],
        'Joomla\\CMS\\Event\\User\\LoginButtonsEvent' => [
            'order'       => ['subject'],
            'getters'     => ['subject' => 'getFormId'],
            'resultAware' => true,
        ],
        'Joomla\\CMS\\Event\\User\\LoginEvent' => [
            'order'       => ['subject', 'options'],
            'getters'     => ['subject' => 'getAuthenticationResponse', 'options' => 'getOptions'],
            'resultAware' => true,
        ],
        'Joomla\\CMS\\Event\\User\\LoginFailureEvent' => [
            'order'       => ['subject', 'options'],
            'getters'     => ['subject' => 'getAuthenticationResponse', 'options' => 'getOptions'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\User\\LogoutEvent' => [
            'order'       => ['subject', 'options'],
            'getters'     => ['subject' => 'getParameters', 'options' => 'getOptions'],
            'resultAware' => true,
        ],
        'Joomla\\CMS\\Event\\User\\LogoutFailureEvent' => [
            'order'       => ['subject', 'options'],
            'getters'     => ['subject' => 'getParameters', 'options' => 'getOptions'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\User\\UserGroupAfterDeleteEvent' => [
            'order'       => [],
            'getters'     => ['context' => 'getContext', 'subject' => 'getItem'],
            'resultAware' => false,
        ],
        'Joomla\\CMS\\Event\\User\\UserGroupBeforeDeleteEvent' => [
            'order'       => [],
            'getters'     => ['context' => 'getContext', 'subject' => 'getItem'],
            'resultAware' => true,
        ],
        'Joomla\\CMS\\Event\\WebAsset\\WebAssetRegistryAssetChanged' => [
            'order'       => [],
            'getters'     => ['asset' => 'getAsset', 'assetType' => 'getAssetType', 'change' => 'getChange'],
            'resultAware' => false,
        ],
    ];
    // </generated:ARGUMENT_MAP>

    // <generated:EVENT_NAME_MAP>
    /**
     * Maps a Joomla core event name onto its concrete event class.
     *
     * Taken from CoreEventAware::$eventNameToConcreteClass, reduced to the events whose
     * arguments are known in DEFAULT_EVENT_ARGUMENT_MAP.
     *
     * Generated by tools/generate-event-argument-map.php from Joomla 6.1.1.
     * Do not edit by hand — re-run the generator instead.
     *
     * @var array<string, class-string>
     */
    public const DEFAULT_EVENT_NAME_MAP = [
        'onAfterApiRoute'                      => 'Joomla\\CMS\\Event\\Application\\AfterApiRouteEvent',
        'onAfterCheckin'                       => 'Joomla\\CMS\\Event\\Checkin\\AfterCheckinEvent',
        'onAfterCleanModuleList'               => 'Joomla\\CMS\\Event\\Module\\AfterCleanModuleListEvent',
        'onAfterCompress'                      => 'Joomla\\CMS\\Event\\Application\\AfterCompressEvent',
        'onAfterDispatch'                      => 'Joomla\\CMS\\Event\\Application\\AfterDispatchEvent',
        'onAfterExecute'                       => 'Joomla\\CMS\\Event\\Application\\AfterExecuteEvent',
        'onAfterExtensionBoot'                 => 'Joomla\\CMS\\Event\\AfterExtensionBootEvent',
        'onAfterGetMenuTypeOptions'            => 'Joomla\\CMS\\Event\\Menu\\AfterGetMenuTypeOptionsEvent',
        'onAfterInitialise'                    => 'Joomla\\CMS\\Event\\Application\\AfterInitialiseEvent',
        'onAfterModuleList'                    => 'Joomla\\CMS\\Event\\Module\\AfterModuleListEvent',
        'onAfterPurge'                         => 'Joomla\\CMS\\Event\\Cache\\AfterPurgeEvent',
        'onAfterRender'                        => 'Joomla\\CMS\\Event\\Application\\AfterRenderEvent',
        'onAfterRenderModule'                  => 'Joomla\\CMS\\Event\\Module\\AfterRenderModuleEvent',
        'onAfterRenderModules'                 => 'Joomla\\CMS\\Event\\Module\\AfterRenderModulesEvent',
        'onAfterRespond'                       => 'Joomla\\CMS\\Event\\Application\\AfterRespondEvent',
        'onAfterRoute'                         => 'Joomla\\CMS\\Event\\Application\\AfterRouteEvent',
        'onApplicationAfterSave'               => 'Joomla\\CMS\\Event\\Application\\AfterSaveConfigurationEvent',
        'onApplicationBeforeSave'              => 'Joomla\\CMS\\Event\\Application\\BeforeSaveConfigurationEvent',
        'onBeforeApiRoute'                     => 'Joomla\\CMS\\Event\\Application\\BeforeApiRouteEvent',
        'onBeforeCompileHead'                  => 'Joomla\\CMS\\Event\\Application\\BeforeCompileHeadEvent',
        'onBeforeExecute'                      => 'Joomla\\CMS\\Event\\Application\\BeforeExecuteEvent',
        'onBeforeExtensionBoot'                => 'Joomla\\CMS\\Event\\BeforeExtensionBootEvent',
        'onBeforeRender'                       => 'Joomla\\CMS\\Event\\Application\\BeforeRenderEvent',
        'onBeforeRenderMenuItems'              => 'Joomla\\CMS\\Event\\Menu\\BeforeRenderMenuItemsViewEvent',
        'onBeforeRespond'                      => 'Joomla\\CMS\\Event\\Application\\BeforeRespondEvent',
        'onCategoryChangeState'                => 'Joomla\\CMS\\Event\\Model\\AfterCategoryChangeStateEvent',
        'onContentAfterDelete'                 => 'Joomla\\CMS\\Event\\Model\\AfterDeleteEvent',
        'onContentAfterDisplay'                => 'Joomla\\CMS\\Event\\Content\\AfterDisplayEvent',
        'onContentAfterSave'                   => 'Joomla\\CMS\\Event\\Model\\AfterSaveEvent',
        'onContentAfterTitle'                  => 'Joomla\\CMS\\Event\\Content\\AfterTitleEvent',
        'onContentBeforeChangeState'           => 'Joomla\\CMS\\Event\\Model\\BeforeChangeStateEvent',
        'onContentBeforeDelete'                => 'Joomla\\CMS\\Event\\Model\\BeforeDeleteEvent',
        'onContentBeforeDisplay'               => 'Joomla\\CMS\\Event\\Content\\BeforeDisplayEvent',
        'onContentBeforeSave'                  => 'Joomla\\CMS\\Event\\Model\\BeforeSaveEvent',
        'onContentBeforeValidateData'          => 'Joomla\\CMS\\Event\\Model\\BeforeValidateDataEvent',
        'onContentChangeState'                 => 'Joomla\\CMS\\Event\\Model\\AfterChangeStateEvent',
        'onContentCleanCache'                  => 'Joomla\\CMS\\Event\\Model\\AfterCleanCacheEvent',
        'onContentNormaliseRequestData'        => 'Joomla\\CMS\\Event\\Model\\NormaliseRequestDataEvent',
        'onContentPrepare'                     => 'Joomla\\CMS\\Event\\Content\\ContentPrepareEvent',
        'onContentPrepareData'                 => 'Joomla\\CMS\\Event\\Model\\PrepareDataEvent',
        'onContentPrepareForm'                 => 'Joomla\\CMS\\Event\\Model\\PrepareFormEvent',
        'onCustomFieldsAfterPrepareField'      => 'Joomla\\CMS\\Event\\CustomFields\\AfterPrepareFieldEvent',
        'onCustomFieldsBeforePrepareField'     => 'Joomla\\CMS\\Event\\CustomFields\\BeforePrepareFieldEvent',
        'onCustomFieldsPrepareDom'             => 'Joomla\\CMS\\Event\\CustomFields\\PrepareDomEvent',
        'onCustomFieldsPrepareField'           => 'Joomla\\CMS\\Event\\CustomFields\\PrepareFieldEvent',
        'onError'                              => 'Joomla\\CMS\\Event\\ErrorEvent',
        'onExtensionAfterDelete'               => 'Joomla\\CMS\\Event\\Model\\AfterDeleteEvent',
        'onExtensionAfterInstall'              => 'Joomla\\CMS\\Event\\Extension\\AfterInstallEvent',
        'onExtensionAfterSave'                 => 'Joomla\\CMS\\Event\\Model\\AfterSaveEvent',
        'onExtensionAfterUninstall'            => 'Joomla\\CMS\\Event\\Extension\\AfterUninstallEvent',
        'onExtensionAfterUpdate'               => 'Joomla\\CMS\\Event\\Extension\\AfterUpdateEvent',
        'onExtensionBeforeInstall'             => 'Joomla\\CMS\\Event\\Extension\\BeforeInstallEvent',
        'onExtensionBeforeSave'                => 'Joomla\\CMS\\Event\\Model\\BeforeSaveEvent',
        'onExtensionBeforeUninstall'           => 'Joomla\\CMS\\Event\\Extension\\BeforeUninstallEvent',
        'onExtensionBeforeUpdate'              => 'Joomla\\CMS\\Event\\Extension\\BeforeUpdateEvent',
        'onExtensionChangeState'               => 'Joomla\\CMS\\Event\\Model\\BeforeChangeStateEvent',
        'onFinderAfterDelete'                  => 'Joomla\\CMS\\Event\\Finder\\AfterDeleteEvent',
        'onFinderAfterSave'                    => 'Joomla\\CMS\\Event\\Finder\\AfterSaveEvent',
        'onFinderBeforeSave'                   => 'Joomla\\CMS\\Event\\Finder\\BeforeSaveEvent',
        'onFinderChangeState'                  => 'Joomla\\CMS\\Event\\Finder\\AfterChangeStateEvent',
        'onFinderResult'                       => 'Joomla\\CMS\\Event\\Finder\\ResultEvent',
        'onGetStatsData'                       => 'Joomla\\CMS\\Event\\Plugin\\System\\Stats\\GetStatsDataEvent',
        'onInstallerAfterInstaller'            => 'Joomla\\CMS\\Event\\Installer\\AfterInstallerEvent',
        'onInstallerBeforeInstallation'        => 'Joomla\\CMS\\Event\\Installer\\BeforeInstallationEvent',
        'onInstallerBeforeInstaller'           => 'Joomla\\CMS\\Event\\Installer\\BeforeInstallerEvent',
        'onInstallerBeforePackageDownload'     => 'Joomla\\CMS\\Event\\Installer\\BeforePackageDownloadEvent',
        'onJoomlaAfterUpdate'                  => 'Joomla\\CMS\\Event\\Extension\\AfterJoomlaUpdateEvent',
        'onMailBeforeRendering'                => 'Joomla\\CMS\\Event\\Mail\\BeforeRenderingMailTemplateEvent',
        'onPrepareFinderContent'               => 'Joomla\\CMS\\Event\\Finder\\PrepareContentEvent',
        'onPrepareModuleList'                  => 'Joomla\\CMS\\Event\\Module\\PrepareModuleListEvent',
        'onPreprocessMenuItems'                => 'Joomla\\CMS\\Event\\Menu\\PreprocessMenuItemsEvent',
        'onPrivacyCanRemoveData'               => 'Joomla\\CMS\\Event\\Privacy\\CanRemoveDataEvent',
        'onPrivacyCheckPrivacyPolicyPublished' => 'Joomla\\CMS\\Event\\Privacy\\CheckPrivacyPolicyPublishedEvent',
        'onPrivacyExportRequest'               => 'Joomla\\CMS\\Event\\Privacy\\ExportRequestEvent',
        'onPrivacyRemoveData'                  => 'Joomla\\CMS\\Event\\Privacy\\RemoveDataEvent',
        'onRenderModule'                       => 'Joomla\\CMS\\Event\\Module\\BeforeRenderModuleEvent',
        'onSchemaBeforeCompileHead'            => 'Joomla\\CMS\\Event\\Plugin\\System\\Schemaorg\\BeforeCompileHeadEvent',
        'onSchemaPrepareData'                  => 'Joomla\\CMS\\Event\\Plugin\\System\\Schemaorg\\PrepareDataEvent',
        'onSchemaPrepareForm'                  => 'Joomla\\CMS\\Event\\Plugin\\System\\Schemaorg\\PrepareFormEvent',
        'onSchemaPrepareSave'                  => 'Joomla\\CMS\\Event\\Plugin\\System\\Schemaorg\\PrepareSaveEvent',
        'onSubmitContact'                      => 'Joomla\\CMS\\Event\\Contact\\SubmitContactEvent',
        'onUserAfterDelete'                    => 'Joomla\\CMS\\Event\\User\\AfterDeleteEvent',
        'onUserAfterDeleteGroup'               => 'Joomla\\CMS\\Event\\Model\\AfterDeleteEvent',
        'onUserAfterLogin'                     => 'Joomla\\CMS\\Event\\User\\AfterLoginEvent',
        'onUserAfterLogout'                    => 'Joomla\\CMS\\Event\\User\\AfterLogoutEvent',
        'onUserAfterRemind'                    => 'Joomla\\CMS\\Event\\User\\AfterRemindEvent',
        'onUserAfterResetComplete'             => 'Joomla\\CMS\\Event\\User\\AfterResetCompleteEvent',
        'onUserAfterResetRequest'              => 'Joomla\\CMS\\Event\\User\\AfterResetRequestEvent',
        'onUserAfterSave'                      => 'Joomla\\CMS\\Event\\User\\AfterSaveEvent',
        'onUserAfterSaveGroup'                 => 'Joomla\\CMS\\Event\\Model\\AfterSaveEvent',
        'onUserAuthenticate'                   => 'Joomla\\CMS\\Event\\User\\AuthenticationEvent',
        'onUserAuthorisation'                  => 'Joomla\\CMS\\Event\\User\\AuthorisationEvent',
        'onUserAuthorisationFailure'           => 'Joomla\\CMS\\Event\\User\\AuthorisationFailureEvent',
        'onUserBeforeDelete'                   => 'Joomla\\CMS\\Event\\User\\BeforeDeleteEvent',
        'onUserBeforeDeleteGroup'              => 'Joomla\\CMS\\Event\\Model\\BeforeDeleteEvent',
        'onUserBeforeResetComplete'            => 'Joomla\\CMS\\Event\\User\\BeforeResetCompleteEvent',
        'onUserBeforeResetRequest'             => 'Joomla\\CMS\\Event\\User\\BeforeResetRequestEvent',
        'onUserBeforeSave'                     => 'Joomla\\CMS\\Event\\User\\BeforeSaveEvent',
        'onUserBeforeSaveGroup'                => 'Joomla\\CMS\\Event\\Model\\BeforeSaveEvent',
        'onUserLogin'                          => 'Joomla\\CMS\\Event\\User\\LoginEvent',
        'onUserLoginButtons'                   => 'Joomla\\CMS\\Event\\User\\LoginButtonsEvent',
        'onUserLoginFailure'                   => 'Joomla\\CMS\\Event\\User\\LoginFailureEvent',
        'onUserLogout'                         => 'Joomla\\CMS\\Event\\User\\LogoutEvent',
        'onUserLogoutFailure'                  => 'Joomla\\CMS\\Event\\User\\LogoutFailureEvent',
        'onValidateContact'                    => 'Joomla\\CMS\\Event\\Contact\\ValidateContactEvent',
    ];
    // </generated:EVENT_NAME_MAP>

    public function __construct(
        private readonly ReflectionProvider $reflectionProvider,
    ) {
    }

    /**
     * Merges a rule's configured event definitions over the generated defaults.
     *
     * @param mixed $configuration The raw value of the rule's event map option.
     *
     * @return array<string, array{order: string[], getters: array<string, string>, resultAware: bool}>
     */
    public static function mergeConfiguration($configuration): array
    {
        if (!\is_array($configuration)) {
            return self::DEFAULT_EVENT_ARGUMENT_MAP;
        }

        $normalised = [];

        foreach ($configuration as $className => $definition) {
            if (!\is_string($className) || !\is_array($definition)) {
                continue;
            }

            $normalisedDefinition = self::normaliseDefinition($definition);

            if ($normalisedDefinition !== null) {
                $normalised[ltrim($className, '\\')] = $normalisedDefinition;
            }
        }

        // Configured entries override the generated defaults.
        return $normalised + self::DEFAULT_EVENT_ARGUMENT_MAP;
    }

    /**
     * Accepts three notations for a configured event definition:
     *
     *   ['context', 'item']                                   positional, getters by convention
     *   ['context' => 'getContext', 'subject' => 'getItem']    argument name => getter
     *   ['order' => [...], 'getters' => [...]]                 both parts explicitly
     *
     * @param array<mixed> $definition
     *
     * @return array{order: string[], getters: array<string, string>, resultAware: bool}|null
     */
    public static function normaliseDefinition(array $definition): ?array
    {
        $resultAware = (bool) ($definition['resultAware'] ?? false);

        if (isset($definition['order']) || isset($definition['getters'])) {
            $order   = [];
            $getters = [];

            foreach ((array) ($definition['order'] ?? []) as $argumentName) {
                if (\is_string($argumentName)) {
                    $order[] = $argumentName;
                }
            }

            foreach ((array) ($definition['getters'] ?? []) as $argumentName => $getter) {
                if (\is_string($argumentName) && \is_string($getter)) {
                    $getters[$argumentName] = $getter;
                }
            }

            // Fill in getters for order entries that were not given explicitly.
            foreach ($order as $argumentName) {
                $getters[$argumentName] ??= 'get' . ucfirst($argumentName);
            }

            return $getters === [] ? null : ['order' => $order, 'getters' => $getters, 'resultAware' => $resultAware];
        }

        if (array_is_list($definition)) {
            $order   = [];
            $getters = [];

            foreach ($definition as $argumentName) {
                if (!\is_string($argumentName)) {
                    return null;
                }

                $order[]                = $argumentName;
                $getters[$argumentName] = 'get' . ucfirst($argumentName);
            }

            return $getters === [] ? null : ['order' => $order, 'getters' => $getters, 'resultAware' => $resultAware];
        }

        $getters = [];

        foreach ($definition as $argumentName => $getter) {
            if ($argumentName === 'resultAware') {
                continue;
            }

            if (!\is_string($argumentName) || !\is_string($getter)) {
                return null;
            }

            $getters[$argumentName] = $getter;
        }

        if ($getters === []) {
            return null;
        }

        return ['order' => array_keys($getters), 'getters' => $getters, 'resultAware' => $resultAware];
    }

    /**
     * Tells whether the class is one of the base event types that carry no concrete arguments.
     */
    public static function isGenericEventClass(string $className): bool
    {
        return \in_array(ltrim($className, '\\'), self::GENERIC_EVENT_CLASSES, true);
    }

    /**
     * Resolves the argument definition for an event class.
     *
     * Falls back to PHPStan reflection to map a project's own subclass of a known event class
     * onto its mapped ancestor. Reflection is never used to invent a definition.
     *
     * @param array<string, array{order: string[], getters: array<string, string>, resultAware: bool}> $map
     *
     * @return array{order: string[], getters: array<string, string>, resultAware: bool}|null
     */
    public function resolveDefinition(array $map, string $className): ?array
    {
        $className = ltrim($className, '\\');

        if (self::isGenericEventClass($className)) {
            return null;
        }

        if (isset($map[$className])) {
            return $map[$className];
        }

        if (!$this->reflectionProvider->hasClass($className)) {
            return null;
        }

        foreach ($this->reflectionProvider->getClass($className)->getParents() as $parentReflection) {
            $parentName = $parentReflection->getName();

            if (self::isGenericEventClass($parentName)) {
                return null;
            }

            if (isset($map[$parentName])) {
                return $map[$parentName];
            }
        }

        return null;
    }

    /**
     * Resolves a Joomla event name such as `onContentPrepare` to its concrete event class.
     *
     * @param array<string, string> $extraNameMap Additional or overriding event name => class entries.
     */
    public function resolveEventClassByName(string $eventName, array $extraNameMap = []): ?string
    {
        if (isset($extraNameMap[$eventName])) {
            return ltrim($extraNameMap[$eventName], '\\');
        }

        return self::DEFAULT_EVENT_NAME_MAP[$eventName] ?? null;
    }
}
