<?php
/**
 * @package     Acme.Example
 * @subpackage  Site
 *
 * @copyright   (C) 2024 Acme, Inc.
 * @license     GNU General Public License version 2 or later
 */
defined('_JEXEC') or die;
$items = $this->items;
-----
<?php
/**
 * @package     Acme.Example
 * @subpackage  Site
 *
 * @copyright   (C) 2024 Acme, Inc.
 * @license     GNU General Public License version 2 or later
 */
/** @var \Acme\Component\Example\Site\View\Articles\HtmlView $this */
defined('_JEXEC') or die;
$items = $this->items;