<?php

/**
 * @package     Joomla.Rector
 * @subpackage  Joomla6
 *
 * @copyright   (C) 2026 Open Source Matters, Inc. <https://www.joomla.org>
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

declare(strict_types=1);

namespace Joomla\Rector\Joomla6\Plugin;

use PhpParser\Node;
use PhpParser\Node\Arg;
use PhpParser\Node\ArrayItem;
use PhpParser\Node\Expr;
use PhpParser\Node\Expr\ArrayDimFetch;
use PhpParser\Node\Expr\Assign;
use PhpParser\Node\Expr\AssignOp;
use PhpParser\Node\Expr\AssignRef;
use PhpParser\Node\Expr\Empty_;
use PhpParser\Node\Expr\FuncCall;
use PhpParser\Node\Expr\Isset_;
use PhpParser\Node\Expr\List_;
use PhpParser\Node\Expr\MethodCall;
use PhpParser\Node\Expr\PostDec;
use PhpParser\Node\Expr\PostInc;
use PhpParser\Node\Expr\PreDec;
use PhpParser\Node\Expr\PreInc;
use PhpParser\Node\Expr\PropertyFetch;
use PhpParser\Node\Expr\Variable;
use PhpParser\Node\FunctionLike;
use PhpParser\Node\Name;
use PhpParser\Node\Scalar\String_;
use PhpParser\Node\Stmt\ClassMethod;
use PhpParser\Node\Stmt\Expression;
use PhpParser\Node\Stmt\Unset_;
use PhpParser\NodeVisitor;
use PHPStan\Reflection\ReflectionProvider;
use Rector\Contract\Rector\ConfigurableRectorInterface;
use Rector\Rector\AbstractRector;
use Symplify\RuleDocGenerator\ValueObject\CodeSample\ConfiguredCodeSample;
use Symplify\RuleDocGenerator\ValueObject\RuleDefinition;

/**
 * Replaces positional and named access to event arguments with the typed getters of the
 * concrete event class.
 *
 * Joomla 4 and 5 guaranteed through the `$legacyArgumentsOrder` property of the concrete event
 * classes that the order of the event arguments matches the parameter order of the old plugin
 * methods. Joomla 6 drops that guarantee, so code relying on the argument order breaks silently.
 *
 * Handled inside methods that receive a typed event parameter:
 *
 *   [$context, $item] = array_values($event->getArguments());  =>  individual getter assignments
 *   [$context, $item] = $event->getArguments();                =>  individual getter assignments
 *   $event->getArgument('context')                             =>  $event->getContext()
 *   $event['context']                                          =>  $event->getContext()
 *
 * The argument name => getter mapping cannot be derived from the argument name alone:
 * ContentPrepareEvent stores its argument as `subject` but exposes it as `getItem()`. The rule
 * therefore resolves the getters from a map generated from the Joomla core source
 * (see tools/generate-event-argument-map.php) and uses PHPStan reflection only to map a subclass
 * of a known event class onto its mapped ancestor.
 *
 * @since  1.0.0
 * @see    \Joomla\Rector\Tests\Joomla6\Plugin\EventArgumentsToTypedEventRector\EventArgumentsToTypedEventRectorTest
 */
final class EventArgumentsToTypedEventRector extends AbstractRector implements ConfigurableRectorInterface
{
    /**
     * Configuration key for additional or overriding event definitions.
     */
    public const EVENT_ARGUMENT_MAP = 'event_argument_map';

    /**
     * Event classes that are too generic to determine the concrete argument list from.
     *
     * A handler typed against one of these is left untouched — typing the signature is the job
     * of LegacyHandlerSignatureRector.
     */
    private const GENERIC_EVENT_CLASSES = [
        'Joomla\\Event\\Event',
        'Joomla\\Event\\EventInterface',
        'Joomla\\Event\\AbstractEvent',
        'Joomla\\Event\\EventImmutable',
        'Joomla\\CMS\\Event\\AbstractEvent',
        'Joomla\\CMS\\Event\\AbstractImmutableEvent',
        'Joomla\\CMS\\Event\\GenericEvent',
    ];

    /**
     * Default argument map for the Joomla core events.
     *
     * Generated by tools/generate-event-argument-map.php from Joomla 6.1.1.
     * Do not edit by hand — re-run the generator instead.
     *
     * @var array<class-string, array{order: string[], getters: array<string, string>}>
     */
    private const DEFAULT_EVENT_ARGUMENT_MAP = [
        'Joomla\\CMS\\Event\\AfterExtensionBootEvent' => [
            'order'   => [],
            'getters' => ['type' => 'getExtensionType', 'extensionName' => 'getExtensionName', 'container' => 'getContainer'],
        ],
        'Joomla\\CMS\\Event\\Application\\AfterApiRouteEvent' => [
            'order'   => [],
            'getters' => ['subject' => 'getApplication'],
        ],
        'Joomla\\CMS\\Event\\Application\\AfterCompressEvent' => [
            'order'   => [],
            'getters' => ['subject' => 'getApplication'],
        ],
        'Joomla\\CMS\\Event\\Application\\AfterDispatchEvent' => [
            'order'   => [],
            'getters' => ['subject' => 'getApplication'],
        ],
        'Joomla\\CMS\\Event\\Application\\AfterExecuteEvent' => [
            'order'   => [],
            'getters' => ['subject' => 'getApplication'],
        ],
        'Joomla\\CMS\\Event\\Application\\AfterInitialiseDocumentEvent' => [
            'order'   => [],
            'getters' => ['subject' => 'getApplication', 'document' => 'getDocument'],
        ],
        'Joomla\\CMS\\Event\\Application\\AfterInitialiseEvent' => [
            'order'   => [],
            'getters' => ['subject' => 'getApplication'],
        ],
        'Joomla\\CMS\\Event\\Application\\AfterRenderEvent' => [
            'order'   => [],
            'getters' => ['subject' => 'getApplication'],
        ],
        'Joomla\\CMS\\Event\\Application\\AfterRespondEvent' => [
            'order'   => [],
            'getters' => ['subject' => 'getApplication'],
        ],
        'Joomla\\CMS\\Event\\Application\\AfterRouteEvent' => [
            'order'   => [],
            'getters' => ['subject' => 'getApplication'],
        ],
        'Joomla\\CMS\\Event\\Application\\AfterSaveConfigurationEvent' => [
            'order'   => [],
            'getters' => ['subject' => 'getConfiguration'],
        ],
        'Joomla\\CMS\\Event\\Application\\ApplicationConfigurationEvent' => [
            'order'   => [],
            'getters' => ['subject' => 'getConfiguration'],
        ],
        'Joomla\\CMS\\Event\\Application\\ApplicationDocumentEvent' => [
            'order'   => [],
            'getters' => ['subject' => 'getApplication', 'document' => 'getDocument'],
        ],
        'Joomla\\CMS\\Event\\Application\\ApplicationEvent' => [
            'order'   => [],
            'getters' => ['subject' => 'getApplication'],
        ],
        'Joomla\\CMS\\Event\\Application\\BeforeApiRouteEvent' => [
            'order'   => [],
            'getters' => ['subject' => 'getApplication', 'router' => 'getRouter'],
        ],
        'Joomla\\CMS\\Event\\Application\\BeforeCompileHeadEvent' => [
            'order'   => [],
            'getters' => ['subject' => 'getApplication', 'document' => 'getDocument'],
        ],
        'Joomla\\CMS\\Event\\Application\\BeforeExecuteEvent' => [
            'order'   => [],
            'getters' => ['subject' => 'getApplication', 'container' => 'getContainer'],
        ],
        'Joomla\\CMS\\Event\\Application\\BeforeRenderEvent' => [
            'order'   => [],
            'getters' => ['subject' => 'getApplication'],
        ],
        'Joomla\\CMS\\Event\\Application\\BeforeRespondEvent' => [
            'order'   => [],
            'getters' => ['subject' => 'getApplication'],
        ],
        'Joomla\\CMS\\Event\\Application\\BeforeSaveConfigurationEvent' => [
            'order'   => [],
            'getters' => ['subject' => 'getConfiguration'],
        ],
        'Joomla\\CMS\\Event\\Application\\DaemonForkEvent' => [
            'order'   => [],
            'getters' => ['subject' => 'getApplication'],
        ],
        'Joomla\\CMS\\Event\\Application\\DaemonReceiveSignalEvent' => [
            'order'   => [],
            'getters' => ['subject' => 'getApplication', 'signal' => 'getSignal'],
        ],
        'Joomla\\CMS\\Event\\BeforeExtensionBootEvent' => [
            'order'   => [],
            'getters' => ['type' => 'getExtensionType', 'extensionName' => 'getExtensionName', 'container' => 'getContainer'],
        ],
        'Joomla\\CMS\\Event\\Cache\\AfterPurgeEvent' => [
            'order'   => ['subject'],
            'getters' => ['subject' => 'getGroup'],
        ],
        'Joomla\\CMS\\Event\\Captcha\\CaptchaSetupEvent' => [
            'order'   => [],
            'getters' => ['subject' => 'getCaptchaRegistry'],
        ],
        'Joomla\\CMS\\Event\\Checkin\\AfterCheckinEvent' => [
            'order'   => ['subject'],
            'getters' => ['subject' => 'getTableName'],
        ],
        'Joomla\\CMS\\Event\\Contact\\SubmitContactEvent' => [
            'order'   => ['subject', 'data'],
            'getters' => ['subject' => 'getContact', 'data' => 'getData'],
        ],
        'Joomla\\CMS\\Event\\Contact\\ValidateContactEvent' => [
            'order'   => ['subject', 'data'],
            'getters' => ['subject' => 'getContact', 'data' => 'getData'],
        ],
        'Joomla\\CMS\\Event\\Content\\AfterDisplayEvent' => [
            'order'   => ['context', 'subject', 'params', 'page'],
            'getters' => ['context' => 'getContext', 'subject' => 'getItem', 'params' => 'getParams', 'page' => 'getPage'],
        ],
        'Joomla\\CMS\\Event\\Content\\AfterTitleEvent' => [
            'order'   => ['context', 'subject', 'params', 'page'],
            'getters' => ['context' => 'getContext', 'subject' => 'getItem', 'params' => 'getParams', 'page' => 'getPage'],
        ],
        'Joomla\\CMS\\Event\\Content\\BeforeDisplayEvent' => [
            'order'   => ['context', 'subject', 'params', 'page'],
            'getters' => ['context' => 'getContext', 'subject' => 'getItem', 'params' => 'getParams', 'page' => 'getPage'],
        ],
        'Joomla\\CMS\\Event\\Content\\ContentEvent' => [
            'order'   => [],
            'getters' => ['context' => 'getContext'],
        ],
        'Joomla\\CMS\\Event\\Content\\ContentPrepareEvent' => [
            'order'   => ['context', 'subject', 'params', 'page'],
            'getters' => ['context' => 'getContext', 'subject' => 'getItem', 'params' => 'getParams', 'page' => 'getPage'],
        ],
        'Joomla\\CMS\\Event\\CustomFields\\AbstractPrepareFieldEvent' => [
            'order'   => ['context', 'item', 'subject'],
            'getters' => ['subject' => 'getField', 'context' => 'getContext', 'item' => 'getItem'],
        ],
        'Joomla\\CMS\\Event\\CustomFields\\AfterPrepareFieldEvent' => [
            'order'   => ['context', 'item', 'subject', 'value'],
            'getters' => ['subject' => 'getField', 'context' => 'getContext', 'item' => 'getItem', 'value' => 'getValue'],
        ],
        'Joomla\\CMS\\Event\\CustomFields\\BeforePrepareFieldEvent' => [
            'order'   => ['context', 'item', 'subject'],
            'getters' => ['subject' => 'getField', 'context' => 'getContext', 'item' => 'getItem'],
        ],
        'Joomla\\CMS\\Event\\CustomFields\\PrepareDomEvent' => [
            'order'   => ['subject', 'fieldset', 'form'],
            'getters' => ['subject' => 'getField', 'fieldset' => 'getFieldset', 'form' => 'getForm'],
        ],
        'Joomla\\CMS\\Event\\CustomFields\\PrepareFieldEvent' => [
            'order'   => ['context', 'item', 'subject'],
            'getters' => ['subject' => 'getField', 'context' => 'getContext', 'item' => 'getItem'],
        ],
        'Joomla\\CMS\\Event\\Editor\\EditorButtonsSetupEvent' => [
            'order'   => [],
            'getters' => ['subject' => 'getButtonsRegistry', 'editorType' => 'getEditorType', 'disabledButtons' => 'getDisabledButtons', 'editorId' => 'getEditorId', 'asset' => 'getAsset', 'author' => 'getAuthor'],
        ],
        'Joomla\\CMS\\Event\\Editor\\EditorSetupEvent' => [
            'order'   => [],
            'getters' => ['subject' => 'getEditorsRegistry'],
        ],
        'Joomla\\CMS\\Event\\ErrorEvent' => [
            'order'   => [],
            'getters' => ['application' => 'getApplication', 'subject' => 'getError'],
        ],
        'Joomla\\CMS\\Event\\Extension\\AfterInstallEvent' => [
            'order'   => ['installer', 'eid'],
            'getters' => ['installer' => 'getInstaller', 'eid' => 'getEid'],
        ],
        'Joomla\\CMS\\Event\\Extension\\AfterJoomlaUpdateEvent' => [
            'order'   => ['oldVersion'],
            'getters' => ['oldVersion' => 'getOldVersion'],
        ],
        'Joomla\\CMS\\Event\\Extension\\AfterUninstallEvent' => [
            'order'   => ['installer', 'eid', 'removed'],
            'getters' => ['installer' => 'getInstaller', 'eid' => 'getEid', 'removed' => 'getRemoved'],
        ],
        'Joomla\\CMS\\Event\\Extension\\AfterUpdateEvent' => [
            'order'   => ['installer', 'eid'],
            'getters' => ['installer' => 'getInstaller', 'eid' => 'getEid'],
        ],
        'Joomla\\CMS\\Event\\Extension\\BeforeInstallEvent' => [
            'order'   => ['method', 'type', 'manifest', 'extension'],
            'getters' => ['method' => 'getMethod', 'type' => 'getType', 'manifest' => 'getManifest', 'extension' => 'getExtension'],
        ],
        'Joomla\\CMS\\Event\\Extension\\BeforeUninstallEvent' => [
            'order'   => ['eid'],
            'getters' => ['eid' => 'getEid'],
        ],
        'Joomla\\CMS\\Event\\Extension\\BeforeUpdateEvent' => [
            'order'   => ['type', 'manifest'],
            'getters' => ['type' => 'getType', 'manifest' => 'getManifest'],
        ],
        'Joomla\\CMS\\Event\\Finder\\AfterChangeStateEvent' => [
            'order'   => ['context', 'subject', 'value'],
            'getters' => ['context' => 'getContext', 'subject' => 'getPks', 'value' => 'getValue'],
        ],
        'Joomla\\CMS\\Event\\Finder\\AfterDeleteEvent' => [
            'order'   => ['context', 'subject'],
            'getters' => ['context' => 'getContext', 'subject' => 'getItem'],
        ],
        'Joomla\\CMS\\Event\\Finder\\AfterSaveEvent' => [
            'order'   => ['context', 'subject', 'isNew'],
            'getters' => ['context' => 'getContext', 'subject' => 'getItem', 'isNew' => 'getIsNew', 'data' => 'getData'],
        ],
        'Joomla\\CMS\\Event\\Finder\\BeforeSaveEvent' => [
            'order'   => ['context', 'subject', 'isNew'],
            'getters' => ['context' => 'getContext', 'subject' => 'getItem', 'isNew' => 'getIsNew', 'data' => 'getData'],
        ],
        'Joomla\\CMS\\Event\\Finder\\PrepareContentEvent' => [
            'order'   => ['subject'],
            'getters' => ['subject' => 'getItem'],
        ],
        'Joomla\\CMS\\Event\\Finder\\ResultEvent' => [
            'order'   => ['subject', 'query'],
            'getters' => ['subject' => 'getItem', 'query' => 'getQuery'],
        ],
        'Joomla\\CMS\\Event\\Installer\\AfterInstallerEvent' => [
            'order'   => ['subject', 'package', 'installer', 'installerResult', 'message'],
            'getters' => ['subject' => 'getModel', 'package' => 'getPackage', 'installer' => 'getInstaller', 'installerResult' => 'getInstallerResult', 'message' => 'getMessage'],
        ],
        'Joomla\\CMS\\Event\\Installer\\BeforeInstallationEvent' => [
            'order'   => ['subject', 'package'],
            'getters' => ['subject' => 'getModel', 'package' => 'getPackage'],
        ],
        'Joomla\\CMS\\Event\\Installer\\BeforeInstallerEvent' => [
            'order'   => ['subject', 'package'],
            'getters' => ['subject' => 'getModel', 'package' => 'getPackage'],
        ],
        'Joomla\\CMS\\Event\\Installer\\BeforePackageDownloadEvent' => [
            'order'   => ['url', 'headers'],
            'getters' => ['url' => 'getUrl', 'headers' => 'getHeaders'],
        ],
        'Joomla\\CMS\\Event\\Installer\\BeforeUpdateSiteDownloadEvent' => [
            'order'   => ['url', 'headers'],
            'getters' => ['url' => 'getUrl', 'headers' => 'getHeaders'],
        ],
        'Joomla\\CMS\\Event\\Installer\\InstallerEvent' => [
            'order'   => ['subject', 'package'],
            'getters' => ['subject' => 'getModel', 'package' => 'getPackage'],
        ],
        'Joomla\\CMS\\Event\\Mail\\BeforeRenderingMailTemplateEvent' => [
            'order'   => ['templateId', 'subject'],
            'getters' => ['subject' => 'getTemplate', 'templateId' => 'getTemplateId'],
        ],
        'Joomla\\CMS\\Event\\Mail\\MailTemplateEvent' => [
            'order'   => [],
            'getters' => ['subject' => 'getTemplate', 'templateId' => 'getTemplateId'],
        ],
        'Joomla\\CMS\\Event\\Menu\\AfterGetMenuTypeOptionsEvent' => [
            'order'   => ['items', 'subject'],
            'getters' => ['subject' => 'getModel', 'items' => 'getItems'],
        ],
        'Joomla\\CMS\\Event\\Menu\\BeforeRenderMenuItemsViewEvent' => [
            'order'   => ['subject'],
            'getters' => ['subject' => 'getView'],
        ],
        'Joomla\\CMS\\Event\\Menu\\PreprocessMenuItemsEvent' => [
            'order'   => ['context', 'subject', 'params', 'enabled'],
            'getters' => ['context' => 'getContext', 'subject' => 'getItems', 'params' => 'getParams', 'enabled' => 'getEnabled'],
        ],
        'Joomla\\CMS\\Event\\Model\\AfterCategoryChangeStateEvent' => [
            'order'   => ['context', 'subject', 'value'],
            'getters' => ['context' => 'getContext', 'subject' => 'getPks', 'value' => 'getValue'],
        ],
        'Joomla\\CMS\\Event\\Model\\AfterChangeStateEvent' => [
            'order'   => ['context', 'subject', 'value'],
            'getters' => ['context' => 'getContext', 'subject' => 'getPks', 'value' => 'getValue'],
        ],
        'Joomla\\CMS\\Event\\Model\\AfterCleanCacheEvent' => [
            'order'   => ['defaultgroup', 'cachebase', 'result'],
            'getters' => ['defaultgroup' => 'getDefaultGroup', 'cachebase' => 'getCacheBase'],
        ],
        'Joomla\\CMS\\Event\\Model\\AfterDeleteEvent' => [
            'order'   => ['context', 'subject'],
            'getters' => ['context' => 'getContext', 'subject' => 'getItem'],
        ],
        'Joomla\\CMS\\Event\\Model\\AfterSaveEvent' => [
            'order'   => ['context', 'subject', 'isNew', 'data'],
            'getters' => ['context' => 'getContext', 'subject' => 'getItem', 'isNew' => 'getIsNew', 'data' => 'getData'],
        ],
        'Joomla\\CMS\\Event\\Model\\BeforeChangeStateEvent' => [
            'order'   => ['context', 'subject', 'value'],
            'getters' => ['context' => 'getContext', 'subject' => 'getPks', 'value' => 'getValue'],
        ],
        'Joomla\\CMS\\Event\\Model\\BeforeDeleteEvent' => [
            'order'   => ['context', 'subject'],
            'getters' => ['context' => 'getContext', 'subject' => 'getItem'],
        ],
        'Joomla\\CMS\\Event\\Model\\BeforeSaveEvent' => [
            'order'   => ['context', 'subject', 'isNew', 'data'],
            'getters' => ['context' => 'getContext', 'subject' => 'getItem', 'isNew' => 'getIsNew', 'data' => 'getData'],
        ],
        'Joomla\\CMS\\Event\\Model\\BeforeValidateDataEvent' => [
            'order'   => ['subject', 'data'],
            'getters' => ['context' => 'getContext', 'subject' => 'getForm', 'data' => 'getData'],
        ],
        'Joomla\\CMS\\Event\\Model\\ChangeStateEvent' => [
            'order'   => ['context', 'subject', 'value'],
            'getters' => ['context' => 'getContext', 'subject' => 'getPks', 'value' => 'getValue'],
        ],
        'Joomla\\CMS\\Event\\Model\\DeleteEvent' => [
            'order'   => ['context', 'subject'],
            'getters' => ['context' => 'getContext', 'subject' => 'getItem'],
        ],
        'Joomla\\CMS\\Event\\Model\\FormEvent' => [
            'order'   => ['subject', 'data'],
            'getters' => ['context' => 'getContext', 'subject' => 'getForm', 'data' => 'getData'],
        ],
        'Joomla\\CMS\\Event\\Model\\ModelEvent' => [
            'order'   => [],
            'getters' => ['context' => 'getContext'],
        ],
        'Joomla\\CMS\\Event\\Model\\NormaliseRequestDataEvent' => [
            'order'   => ['context', 'data', 'subject'],
            'getters' => ['context' => 'getContext', 'subject' => 'getForm', 'data' => 'getData'],
        ],
        'Joomla\\CMS\\Event\\Model\\PrepareDataEvent' => [
            'order'   => ['context', 'data'],
            'getters' => ['context' => 'getContext', 'data' => 'getData'],
        ],
        'Joomla\\CMS\\Event\\Model\\PrepareFormEvent' => [
            'order'   => ['subject', 'data'],
            'getters' => ['context' => 'getContext', 'subject' => 'getForm', 'data' => 'getData'],
        ],
        'Joomla\\CMS\\Event\\Model\\SaveEvent' => [
            'order'   => ['context', 'subject', 'isNew', 'data'],
            'getters' => ['context' => 'getContext', 'subject' => 'getItem', 'isNew' => 'getIsNew', 'data' => 'getData'],
        ],
        'Joomla\\CMS\\Event\\Module\\AfterCleanModuleListEvent' => [
            'order'   => ['modules'],
            'getters' => ['modules' => 'getModules'],
        ],
        'Joomla\\CMS\\Event\\Module\\AfterModuleListEvent' => [
            'order'   => ['modules'],
            'getters' => ['modules' => 'getModules'],
        ],
        'Joomla\\CMS\\Event\\Module\\AfterRenderModuleEvent' => [
            'order'   => ['subject', 'attributes'],
            'getters' => ['subject' => 'getModule', 'attributes' => 'getAttributes'],
        ],
        'Joomla\\CMS\\Event\\Module\\AfterRenderModulesEvent' => [
            'order'   => ['content', 'attributes'],
            'getters' => ['content' => 'getContent', 'attributes' => 'getAttributes'],
        ],
        'Joomla\\CMS\\Event\\Module\\BeforeRenderModuleEvent' => [
            'order'   => ['subject', 'attributes'],
            'getters' => ['subject' => 'getModule', 'attributes' => 'getAttributes'],
        ],
        'Joomla\\CMS\\Event\\Module\\ModuleListEvent' => [
            'order'   => ['modules'],
            'getters' => ['modules' => 'getModules'],
        ],
        'Joomla\\CMS\\Event\\Module\\PrepareModuleListEvent' => [
            'order'   => ['modules'],
            'getters' => ['modules' => 'getModules'],
        ],
        'Joomla\\CMS\\Event\\Module\\RenderModuleEvent' => [
            'order'   => ['subject', 'attributes'],
            'getters' => ['subject' => 'getModule', 'attributes' => 'getAttributes'],
        ],
        'Joomla\\CMS\\Event\\Plugin\\AjaxEvent' => [
            'order'   => [],
            'getters' => ['subject' => 'getApplication'],
        ],
        'Joomla\\CMS\\Event\\Plugin\\System\\Schemaorg\\BeforeCompileHeadEvent' => [
            'order'   => [],
            'getters' => ['subject' => 'getSchema', 'context' => 'getContext'],
        ],
        'Joomla\\CMS\\Event\\Plugin\\System\\Schemaorg\\PrepareDataEvent' => [
            'order'   => [],
            'getters' => ['subject' => 'getData', 'context' => 'getContext'],
        ],
        'Joomla\\CMS\\Event\\Plugin\\System\\Schemaorg\\PrepareFormEvent' => [
            'order'   => [],
            'getters' => ['subject' => 'getForm'],
        ],
        'Joomla\\CMS\\Event\\Plugin\\System\\Schemaorg\\PrepareSaveEvent' => [
            'order'   => [],
            'getters' => ['subject' => 'getData', 'context' => 'getContext', 'item' => 'getItem', 'isNew' => 'getIsNew', 'schema' => 'getSchema'],
        ],
        'Joomla\\CMS\\Event\\Plugin\\System\\Stats\\GetStatsDataEvent' => [
            'order'   => ['context'],
            'getters' => ['context' => 'getContext'],
        ],
        'Joomla\\CMS\\Event\\Privacy\\CanRemoveDataEvent' => [
            'order'   => ['subject', 'user'],
            'getters' => ['subject' => 'getRequest', 'user' => 'getUser'],
        ],
        'Joomla\\CMS\\Event\\Privacy\\CheckPrivacyPolicyPublishedEvent' => [
            'order'   => ['subject'],
            'getters' => ['subject' => 'getPolicyInfo'],
        ],
        'Joomla\\CMS\\Event\\Privacy\\ExportRequestEvent' => [
            'order'   => ['subject', 'user'],
            'getters' => ['subject' => 'getRequest', 'user' => 'getUser'],
        ],
        'Joomla\\CMS\\Event\\Privacy\\RemoveDataEvent' => [
            'order'   => ['subject', 'user'],
            'getters' => ['subject' => 'getRequest', 'user' => 'getUser'],
        ],
        'Joomla\\CMS\\Event\\User\\AbstractDeleteEvent' => [
            'order'   => ['subject'],
            'getters' => ['subject' => 'getUser'],
        ],
        'Joomla\\CMS\\Event\\User\\AbstractLoginEvent' => [
            'order'   => ['subject', 'options'],
            'getters' => ['subject' => 'getAuthenticationResponse', 'options' => 'getOptions'],
        ],
        'Joomla\\CMS\\Event\\User\\AbstractLogoutEvent' => [
            'order'   => ['subject', 'options'],
            'getters' => ['subject' => 'getParameters', 'options' => 'getOptions'],
        ],
        'Joomla\\CMS\\Event\\User\\AbstractResetEvent' => [
            'order'   => ['subject'],
            'getters' => ['subject' => 'getUser'],
        ],
        'Joomla\\CMS\\Event\\User\\AbstractSaveEvent' => [
            'order'   => ['subject', 'isNew'],
            'getters' => ['subject' => 'getUser', 'isNew' => 'getIsNew'],
        ],
        'Joomla\\CMS\\Event\\User\\AfterDeleteEvent' => [
            'order'   => ['subject', 'deletingResult', 'errorMessage'],
            'getters' => ['subject' => 'getUser', 'deletingResult' => 'getDeletingResult', 'errorMessage' => 'getErrorMessage'],
        ],
        'Joomla\\CMS\\Event\\User\\AfterLoginEvent' => [
            'order'   => ['options', 'subject'],
            'getters' => ['subject' => 'getAuthenticationResponse', 'options' => 'getOptions'],
        ],
        'Joomla\\CMS\\Event\\User\\AfterLogoutEvent' => [
            'order'   => ['options', 'subject'],
            'getters' => ['subject' => 'getParameters', 'options' => 'getOptions'],
        ],
        'Joomla\\CMS\\Event\\User\\AfterRemindEvent' => [
            'order'   => ['subject'],
            'getters' => ['subject' => 'getUser'],
        ],
        'Joomla\\CMS\\Event\\User\\AfterResetCompleteEvent' => [
            'order'   => ['subject'],
            'getters' => ['subject' => 'getUser'],
        ],
        'Joomla\\CMS\\Event\\User\\AfterResetRequestEvent' => [
            'order'   => ['subject'],
            'getters' => ['subject' => 'getUser'],
        ],
        'Joomla\\CMS\\Event\\User\\AfterSaveEvent' => [
            'order'   => ['subject', 'isNew', 'savingResult', 'errorMessage'],
            'getters' => ['subject' => 'getUser', 'isNew' => 'getIsNew', 'savingResult' => 'getSavingResult', 'errorMessage' => 'getErrorMessage'],
        ],
        'Joomla\\CMS\\Event\\User\\AuthenticationEvent' => [
            'order'   => ['credentials', 'options', 'subject'],
            'getters' => ['subject' => 'getAuthenticationResponse', 'credentials' => 'getCredentials', 'options' => 'getOptions'],
        ],
        'Joomla\\CMS\\Event\\User\\AuthorisationEvent' => [
            'order'   => ['subject', 'options'],
            'getters' => ['subject' => 'getAuthenticationResponse', 'options' => 'getOptions'],
        ],
        'Joomla\\CMS\\Event\\User\\AuthorisationFailureEvent' => [
            'order'   => ['subject', 'options'],
            'getters' => ['subject' => 'getAuthenticationResponse', 'options' => 'getOptions'],
        ],
        'Joomla\\CMS\\Event\\User\\BeforeDeleteEvent' => [
            'order'   => ['subject'],
            'getters' => ['subject' => 'getUser'],
        ],
        'Joomla\\CMS\\Event\\User\\BeforeResetCompleteEvent' => [
            'order'   => ['subject'],
            'getters' => ['subject' => 'getUser'],
        ],
        'Joomla\\CMS\\Event\\User\\BeforeResetRequestEvent' => [
            'order'   => ['subject'],
            'getters' => ['subject' => 'getUser'],
        ],
        'Joomla\\CMS\\Event\\User\\BeforeSaveEvent' => [
            'order'   => ['subject', 'isNew', 'data'],
            'getters' => ['subject' => 'getUser', 'isNew' => 'getIsNew', 'data' => 'getData'],
        ],
        'Joomla\\CMS\\Event\\User\\LoginButtonsEvent' => [
            'order'   => ['subject'],
            'getters' => ['subject' => 'getFormId'],
        ],
        'Joomla\\CMS\\Event\\User\\LoginEvent' => [
            'order'   => ['subject', 'options'],
            'getters' => ['subject' => 'getAuthenticationResponse', 'options' => 'getOptions'],
        ],
        'Joomla\\CMS\\Event\\User\\LoginFailureEvent' => [
            'order'   => ['subject', 'options'],
            'getters' => ['subject' => 'getAuthenticationResponse', 'options' => 'getOptions'],
        ],
        'Joomla\\CMS\\Event\\User\\LogoutEvent' => [
            'order'   => ['subject', 'options'],
            'getters' => ['subject' => 'getParameters', 'options' => 'getOptions'],
        ],
        'Joomla\\CMS\\Event\\User\\LogoutFailureEvent' => [
            'order'   => ['subject', 'options'],
            'getters' => ['subject' => 'getParameters', 'options' => 'getOptions'],
        ],
        'Joomla\\CMS\\Event\\User\\UserGroupAfterDeleteEvent' => [
            'order'   => [],
            'getters' => ['context' => 'getContext', 'subject' => 'getItem'],
        ],
        'Joomla\\CMS\\Event\\User\\UserGroupBeforeDeleteEvent' => [
            'order'   => [],
            'getters' => ['context' => 'getContext', 'subject' => 'getItem'],
        ],
        'Joomla\\CMS\\Event\\WebAsset\\WebAssetRegistryAssetChanged' => [
            'order'   => [],
            'getters' => ['asset' => 'getAsset', 'assetType' => 'getAssetType', 'change' => 'getChange'],
        ],
    ];

    /**
     * The effective map, i.e. the default map merged with the configured one.
     *
     * @var array<string, array{order: string[], getters: array<string, string>}>
     */
    private array $eventArgumentMap = self::DEFAULT_EVENT_ARGUMENT_MAP;

    public function __construct(
        private readonly ReflectionProvider $reflectionProvider,
    ) {
    }

    /**
     * @param array<string, mixed> $configuration
     */
    public function configure(array $configuration): void
    {
        $configuredMap = $configuration[self::EVENT_ARGUMENT_MAP] ?? [];

        if (!\is_array($configuredMap)) {
            return;
        }

        $normalised = [];

        foreach ($configuredMap as $className => $definition) {
            if (!\is_string($className) || !\is_array($definition)) {
                continue;
            }

            $normalisedDefinition = $this->normaliseDefinition($definition);

            if ($normalisedDefinition !== null) {
                $normalised[ltrim($className, '\\')] = $normalisedDefinition;
            }
        }

        // Configured entries override the generated defaults.
        $this->eventArgumentMap = $normalised + self::DEFAULT_EVENT_ARGUMENT_MAP;
    }

    public function getRuleDefinition(): RuleDefinition
    {
        return new RuleDefinition(
            'Replace positional and named event argument access with the typed getters of the concrete event class',
            [
                new ConfiguredCodeSample(
                    <<<'CODE_SAMPLE'
use Joomla\CMS\Event\Content\ContentPrepareEvent;

class PlgContentExample extends CMSPlugin implements SubscriberInterface
{
    public function myOnContentPrepare(ContentPrepareEvent $event)
    {
        [$context, $item, $params, $page] = array_values($event->getArguments());

        if ($context !== 'com_content.article') {
            return;
        }

        $item->text .= 'foo';
    }
}
CODE_SAMPLE,
                    <<<'CODE_SAMPLE'
use Joomla\CMS\Event\Content\ContentPrepareEvent;

class PlgContentExample extends CMSPlugin implements SubscriberInterface
{
    public function myOnContentPrepare(ContentPrepareEvent $event)
    {
        $context = $event->getContext();
        $item = $event->getItem();
        $params = $event->getParams();
        $page = $event->getPage();

        if ($context !== 'com_content.article') {
            return;
        }

        $item->text .= 'foo';
    }
}
CODE_SAMPLE,
                    [
                        self::EVENT_ARGUMENT_MAP => [
                            'Acme\\Event\\MyCustomEvent' => ['context', 'item'],
                        ],
                    ]
                ),
            ]
        );
    }

    /**
     * @return array<class-string<Node>>
     */
    public function getNodeTypes(): array
    {
        return [ClassMethod::class];
    }

    /**
     * @param ClassMethod $node
     */
    public function refactor(Node $node): ?Node
    {
        if ($node->stmts === null || $node->stmts === []) {
            return null;
        }

        $eventVariables = $this->resolveEventVariables($node);

        if ($eventVariables === []) {
            return null;
        }

        $writeTargets = $this->collectArrayDimWriteTargets($node);

        $hasChanged = false;

        // The ClassMethod itself is traversed, not its statement list: replacing a statement
        // with several statements only survives when the traverser can write the new list
        // back into the owning node.
        $this->traverseNodesWithCallable(
            $node,
            function (Node $subNode) use ($node, $eventVariables, $writeTargets, &$hasChanged) {
                // A nested function that declares a parameter of the same name shadows the
                // event variable. Its body describes a different object, so skip the subtree.
                if ($subNode instanceof FunctionLike && $subNode !== $node) {
                    foreach ($subNode->getParams() as $param) {
                        if (
                            $param->var instanceof Variable
                            && \is_string($param->var->name)
                            && isset($eventVariables[$param->var->name])
                        ) {
                            return NodeVisitor::DONT_TRAVERSE_CHILDREN;
                        }
                    }
                }

                if ($subNode instanceof Expression) {
                    $replacement = $this->refactorDestructuring($subNode, $eventVariables);

                    if ($replacement !== null) {
                        $hasChanged = true;

                        return $replacement;
                    }

                    return null;
                }

                if ($subNode instanceof MethodCall) {
                    $replacement = $this->refactorGetArgumentCall($subNode, $eventVariables);

                    if ($replacement !== null) {
                        $hasChanged = true;

                        return $replacement;
                    }

                    return null;
                }

                if ($subNode instanceof ArrayDimFetch && !$writeTargets->contains($subNode)) {
                    $replacement = $this->refactorArrayAccess($subNode, $eventVariables);

                    if ($replacement !== null) {
                        $hasChanged = true;

                        return $replacement;
                    }
                }

                return null;
            }
        );

        return $hasChanged ? $node : null;
    }

    // -------------------------------------------------------------------------
    // Event parameter resolution
    // -------------------------------------------------------------------------

    /**
     * Maps the name of every usable event parameter onto its argument definition.
     *
     * @return array<string, array{order: string[], getters: array<string, string>}>
     */
    private function resolveEventVariables(ClassMethod $classMethod): array
    {
        $eventVariables = [];

        foreach ($classMethod->params as $param) {
            // A by-reference parameter may be re-bound by the caller — leave it alone.
            if ($param->byRef || $param->variadic) {
                continue;
            }

            if (!$param->var instanceof Variable || !\is_string($param->var->name)) {
                continue;
            }

            // Only a plain class type identifies the event class. Nullable, union and
            // intersection types are skipped on purpose.
            if (!$param->type instanceof Name) {
                continue;
            }

            $className = $this->getName($param->type);

            if ($className === null) {
                continue;
            }

            $className = ltrim($className, '\\');

            if (\in_array($className, self::GENERIC_EVENT_CLASSES, true)) {
                continue;
            }

            $definition = $this->resolveDefinition($className);

            if ($definition === null) {
                continue;
            }

            $eventVariables[$param->var->name] = $definition;
        }

        if ($eventVariables === []) {
            return [];
        }

        // Drop every event variable that is reassigned somewhere in the method — from that
        // point on it may no longer hold the event object.
        foreach ($this->collectReassignedVariables($classMethod) as $variableName) {
            unset($eventVariables[$variableName]);
        }

        return $eventVariables;
    }

    /**
     * @return array{order: string[], getters: array<string, string>}|null
     */
    private function resolveDefinition(string $className): ?array
    {
        if (isset($this->eventArgumentMap[$className])) {
            return $this->eventArgumentMap[$className];
        }

        // Reflection is used only to map a subclass of a known event class onto its
        // mapped ancestor, e.g. a project's own MyContentPrepareEvent.
        if (!$this->reflectionProvider->hasClass($className)) {
            return null;
        }

        foreach ($this->reflectionProvider->getClass($className)->getParents() as $parentReflection) {
            $parentName = $parentReflection->getName();

            if (\in_array($parentName, self::GENERIC_EVENT_CLASSES, true)) {
                return null;
            }

            if (isset($this->eventArgumentMap[$parentName])) {
                return $this->eventArgumentMap[$parentName];
            }
        }

        return null;
    }

    // -------------------------------------------------------------------------
    // Transformations
    // -------------------------------------------------------------------------

    /**
     * Rewrites `[$a, $b] = array_values($event->getArguments());` and
     * `[$a, $b] = $event->getArguments();` into one assignment per argument.
     *
     * @param array<string, array{order: string[], getters: array<string, string>}> $eventVariables
     *
     * @return Expression[]|null
     */
    private function refactorDestructuring(Expression $expression, array $eventVariables): ?array
    {
        if (!$expression->expr instanceof Assign) {
            return null;
        }

        $assign = $expression->expr;

        if (!$assign->var instanceof List_) {
            return null;
        }

        $eventVariableName = $this->matchGetArgumentsSource($assign->expr, $eventVariables);

        if ($eventVariableName === null) {
            return null;
        }

        $definition = $eventVariables[$eventVariableName];
        $order      = $definition['order'];

        if ($order === []) {
            return null;
        }

        $items = $assign->var->items;

        // More targets than known arguments — the argument list does not match, skip.
        if (\count($items) > \count($order)) {
            return null;
        }

        $targets = [];

        foreach ($items as $position => $item) {
            // Holes (`[$a, , $c]`) and keyed or by-reference targets are out of scope.
            if (!$item instanceof ArrayItem || $item->key !== null || $item->byRef) {
                return null;
            }

            // Nested destructuring cannot be mapped onto a single getter.
            if (!$item->value instanceof Variable && !$item->value instanceof PropertyFetch) {
                return null;
            }

            $argumentName = $order[$position];
            $getter       = $definition['getters'][$argumentName] ?? null;

            if ($getter === null) {
                return null;
            }

            $targets[] = [$item->value, $getter];
        }

        if ($targets === []) {
            return null;
        }

        $statements = [];

        foreach ($targets as $index => [$target, $getter]) {
            $assign = new Assign($target, new MethodCall(new Variable($eventVariableName), $getter));

            if ($index === 0) {
                // Reuse the original statement for the first assignment. It keeps its position
                // and its comments, so the surrounding blank lines and docblock survive.
                $expression->expr = $assign;
                $statements[]     = $expression;

                continue;
            }

            $statements[] = new Expression($assign);
        }

        return $statements;
    }

    /**
     * Returns the event variable name when the expression reads all event arguments,
     * i.e. `$event->getArguments()` or `array_values($event->getArguments())`.
     *
     * @param array<string, array{order: string[], getters: array<string, string>}> $eventVariables
     */
    private function matchGetArgumentsSource(Expr $expr, array $eventVariables): ?string
    {
        if ($expr instanceof FuncCall) {
            if (!$this->isName($expr, 'array_values') || \count($expr->args) !== 1) {
                return null;
            }

            $firstArg = $expr->args[0];

            if (!$firstArg instanceof Arg) {
                return null;
            }

            $expr = $firstArg->value;
        }

        if (!$expr instanceof MethodCall || $expr->args !== []) {
            return null;
        }

        if (!$this->isName($expr->name, 'getArguments')) {
            return null;
        }

        return $this->matchEventVariable($expr->var, $eventVariables);
    }

    /**
     * Rewrites `$event->getArgument('context')` into `$event->getContext()`.
     *
     * @param array<string, array{order: string[], getters: array<string, string>}> $eventVariables
     */
    private function refactorGetArgumentCall(MethodCall $methodCall, array $eventVariables): ?MethodCall
    {
        if (!$this->isName($methodCall->name, 'getArgument')) {
            return null;
        }

        // A second argument is a default value; the getter has no equivalent for it.
        if (\count($methodCall->args) !== 1) {
            return null;
        }

        $eventVariableName = $this->matchEventVariable($methodCall->var, $eventVariables);

        if ($eventVariableName === null) {
            return null;
        }

        $firstArg = $methodCall->args[0];

        if (!$firstArg instanceof Arg || !$firstArg->value instanceof String_) {
            return null;
        }

        $getter = $this->resolveGetter($firstArg->value->value, $eventVariables[$eventVariableName]);

        if ($getter === null) {
            return null;
        }

        return new MethodCall(new Variable($eventVariableName), $getter);
    }

    /**
     * Rewrites `$event['context']` into `$event->getContext()`.
     *
     * @param array<string, array{order: string[], getters: array<string, string>}> $eventVariables
     */
    private function refactorArrayAccess(ArrayDimFetch $arrayDimFetch, array $eventVariables): ?MethodCall
    {
        if (!$arrayDimFetch->dim instanceof String_) {
            return null;
        }

        $eventVariableName = $this->matchEventVariable($arrayDimFetch->var, $eventVariables);

        if ($eventVariableName === null) {
            return null;
        }

        $getter = $this->resolveGetter($arrayDimFetch->dim->value, $eventVariables[$eventVariableName]);

        if ($getter === null) {
            return null;
        }

        return new MethodCall(new Variable($eventVariableName), $getter);
    }

    /**
     * @param array{order: string[], getters: array<string, string>} $definition
     */
    private function resolveGetter(string $argumentName, array $definition): ?string
    {
        // Numeric access does not identify an argument reliably, see AbstractEvent::getArgument().
        if (is_numeric($argumentName)) {
            return null;
        }

        // The `result` argument belongs to the event result handling, not here.
        if ($argumentName === 'result') {
            return null;
        }

        return $definition['getters'][$argumentName] ?? null;
    }

    /**
     * @param array<string, array{order: string[], getters: array<string, string>}> $eventVariables
     */
    private function matchEventVariable(Expr $expr, array $eventVariables): ?string
    {
        if (!$expr instanceof Variable || !\is_string($expr->name)) {
            return null;
        }

        return isset($eventVariables[$expr->name]) ? $expr->name : null;
    }

    // -------------------------------------------------------------------------
    // Safety analysis
    // -------------------------------------------------------------------------

    /**
     * Collects the names of all variables that are written to inside the method.
     *
     * @return string[]
     */
    private function collectReassignedVariables(ClassMethod $classMethod): array
    {
        $variableNames = [];

        $this->traverseNodesWithCallable($classMethod->stmts, static function (Node $node) use (&$variableNames): ?Node {
            $target = null;

            if ($node instanceof Assign || $node instanceof AssignRef || $node instanceof AssignOp) {
                $target = $node->var;
            } elseif ($node instanceof PreInc || $node instanceof PreDec || $node instanceof PostInc || $node instanceof PostDec) {
                $target = $node->var;
            } elseif ($node instanceof Node\Stmt\Foreach_) {
                $target = $node->valueVar;
            }

            if ($target instanceof Variable && \is_string($target->name)) {
                $variableNames[] = $target->name;
            }

            // A by-reference assignment source may be rebound later as well.
            if ($node instanceof AssignRef && $node->expr instanceof Variable && \is_string($node->expr->name)) {
                $variableNames[] = $node->expr->name;
            }

            return null;
        });

        return $variableNames;
    }

    /**
     * Collects every ArrayDimFetch that is written to, unset or tested rather than read,
     * so `$event['x'] = 1;` or `isset($event['x'])` is never turned into a getter call.
     *
     * @return \SplObjectStorage<ArrayDimFetch, null>
     */
    private function collectArrayDimWriteTargets(ClassMethod $classMethod): \SplObjectStorage
    {
        /** @var \SplObjectStorage<ArrayDimFetch, null> $writeTargets */
        $writeTargets = new \SplObjectStorage();

        $mark = static function (?Expr $expr) use ($writeTargets): void {
            // Mark the whole chain, so `$event['a']['b'] = 1` also protects `$event['a']`.
            while ($expr instanceof ArrayDimFetch) {
                $writeTargets->attach($expr);
                $expr = $expr->var;
            }
        };

        $this->traverseNodesWithCallable($classMethod->stmts, static function (Node $node) use ($mark): ?Node {
            if ($node instanceof Assign || $node instanceof AssignRef || $node instanceof AssignOp) {
                $mark($node->var);
            }

            if ($node instanceof AssignRef) {
                $mark($node->expr);
            }

            if ($node instanceof PreInc || $node instanceof PreDec || $node instanceof PostInc || $node instanceof PostDec) {
                $mark($node->var);
            }

            if ($node instanceof Isset_) {
                foreach ($node->vars as $var) {
                    $mark($var);
                }
            }

            if ($node instanceof Unset_) {
                foreach ($node->vars as $var) {
                    $mark($var);
                }
            }

            if ($node instanceof Empty_) {
                $mark($node->expr);
            }

            return null;
        });

        return $writeTargets;
    }

    // -------------------------------------------------------------------------
    // Configuration handling
    // -------------------------------------------------------------------------

    /**
     * Accepts three notations for a configured event definition:
     *
     *   ['context', 'item']                            positional, getters by convention
     *   ['context' => 'getContext', 'subject' => 'getItem']   argument name => getter
     *   ['order' => [...], 'getters' => [...]]         both parts explicitly
     *
     * @param array<mixed> $definition
     *
     * @return array{order: string[], getters: array<string, string>}|null
     */
    private function normaliseDefinition(array $definition): ?array
    {
        if (isset($definition['order']) || isset($definition['getters'])) {
            $order   = [];
            $getters = [];

            foreach ((array) ($definition['order'] ?? []) as $argumentName) {
                if (\is_string($argumentName)) {
                    $order[] = $argumentName;
                }
            }

            foreach ((array) ($definition['getters'] ?? []) as $argumentName => $getter) {
                if (\is_string($argumentName) && \is_string($getter)) {
                    $getters[$argumentName] = $getter;
                }
            }

            // Fill in getters for order entries that were not given explicitly.
            foreach ($order as $argumentName) {
                $getters[$argumentName] ??= 'get' . ucfirst($argumentName);
            }

            return $getters === [] ? null : ['order' => $order, 'getters' => $getters];
        }

        if (array_is_list($definition)) {
            $order   = [];
            $getters = [];

            foreach ($definition as $argumentName) {
                if (!\is_string($argumentName)) {
                    return null;
                }

                $order[]                = $argumentName;
                $getters[$argumentName] = 'get' . ucfirst($argumentName);
            }

            return $getters === [] ? null : ['order' => $order, 'getters' => $getters];
        }

        $getters = [];

        foreach ($definition as $argumentName => $getter) {
            if (!\is_string($argumentName) || !\is_string($getter)) {
                return null;
            }

            $getters[$argumentName] = $getter;
        }

        return $getters === [] ? null : ['order' => array_keys($getters), 'getters' => $getters];
    }
}
